// Auto-generated for github.com/projectkeas/crds
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IngestionPolicyListerExpansion allows custom methods to be added to
// IngestionPolicyLister.
type IngestionPolicyListerExpansion interface{}

// IngestionPolicyNamespaceListerExpansion allows custom methods to be added to
// IngestionPolicyNamespaceLister.
type IngestionPolicyNamespaceListerExpansion interface{}
