// Auto-generated for github.com/projectkeas/crds
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EventTypeListerExpansion allows custom methods to be added to
// EventTypeLister.
type EventTypeListerExpansion interface{}

// EventTypeNamespaceListerExpansion allows custom methods to be added to
// EventTypeNamespaceLister.
type EventTypeNamespaceListerExpansion interface{}

// IngestionPolicyListerExpansion allows custom methods to be added to
// IngestionPolicyLister.
type IngestionPolicyListerExpansion interface{}

// IngestionPolicyNamespaceListerExpansion allows custom methods to be added to
// IngestionPolicyNamespaceLister.
type IngestionPolicyNamespaceListerExpansion interface{}
