apiVersion: keas.io/v1alpha1
kind: IngestionPolicy
metadata:
  name: test
spec:
  description: |
    this is a test policy in which we can do something
  policy: |
    Hello Policy

    this is me
---
apiVersion: keas.io/v1alpha1
kind: IngestionPolicy
metadata:
  name: test2
spec:
  description: simple policy
  defaults:
    allow: true
    ttl: -1
  policy: |
    Hello Policy

    this is me
---
apiVersion: keas.io/v1alpha1
kind: EventType
metadata:
  name: test
spec:
  description: "Testing 123"
  version: '0.0.1'
  owner: ProjectKeas
  type: Repository
  sources:
    - Gitlab
    - Github
  subTypes:
    - Created
    - Updated
    - Deleted
  schema: |
    {
      "hello": "world"
    }