// Auto-generated for github.com/projectkeas/crds
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/projectkeas/crds/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// EventTypes returns a EventTypeInformer.
	EventTypes() EventTypeInformer
	// IngestionPolicies returns a IngestionPolicyInformer.
	IngestionPolicies() IngestionPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// EventTypes returns a EventTypeInformer.
func (v *version) EventTypes() EventTypeInformer {
	return &eventTypeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IngestionPolicies returns a IngestionPolicyInformer.
func (v *version) IngestionPolicies() IngestionPolicyInformer {
	return &ingestionPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
