// Auto-generated for github.com/projectkeas/crds
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/projectkeas/crds/pkg/apis/keas.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEventTypes implements EventTypeInterface
type FakeEventTypes struct {
	Fake *FakeKeasV1alpha1
	ns   string
}

var eventtypesResource = schema.GroupVersionResource{Group: "keas.io", Version: "v1alpha1", Resource: "eventtypes"}

var eventtypesKind = schema.GroupVersionKind{Group: "keas.io", Version: "v1alpha1", Kind: "EventType"}

// Get takes name of the eventType, and returns the corresponding eventType object, and an error if there is any.
func (c *FakeEventTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EventType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(eventtypesResource, c.ns, name), &v1alpha1.EventType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventType), err
}

// List takes label and field selectors, and returns the list of EventTypes that match those selectors.
func (c *FakeEventTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EventTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(eventtypesResource, eventtypesKind, c.ns, opts), &v1alpha1.EventTypeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EventTypeList{ListMeta: obj.(*v1alpha1.EventTypeList).ListMeta}
	for _, item := range obj.(*v1alpha1.EventTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eventTypes.
func (c *FakeEventTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(eventtypesResource, c.ns, opts))

}

// Create takes the representation of a eventType and creates it.  Returns the server's representation of the eventType, and an error, if there is any.
func (c *FakeEventTypes) Create(ctx context.Context, eventType *v1alpha1.EventType, opts v1.CreateOptions) (result *v1alpha1.EventType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(eventtypesResource, c.ns, eventType), &v1alpha1.EventType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventType), err
}

// Update takes the representation of a eventType and updates it. Returns the server's representation of the eventType, and an error, if there is any.
func (c *FakeEventTypes) Update(ctx context.Context, eventType *v1alpha1.EventType, opts v1.UpdateOptions) (result *v1alpha1.EventType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(eventtypesResource, c.ns, eventType), &v1alpha1.EventType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventType), err
}

// Delete takes name of the eventType and deletes it. Returns an error if one occurs.
func (c *FakeEventTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(eventtypesResource, c.ns, name, opts), &v1alpha1.EventType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEventTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(eventtypesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EventTypeList{})
	return err
}

// Patch applies the patch and returns the patched eventType.
func (c *FakeEventTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EventType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(eventtypesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EventType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventType), err
}
