// Auto-generated for github.com/projectkeas/crds
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/projectkeas/crds/pkg/apis/keas.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIngestionPolicies implements IngestionPolicyInterface
type FakeIngestionPolicies struct {
	Fake *FakeKeasV1alpha1
	ns   string
}

var ingestionpoliciesResource = schema.GroupVersionResource{Group: "keas.io", Version: "v1alpha1", Resource: "ingestionpolicies"}

var ingestionpoliciesKind = schema.GroupVersionKind{Group: "keas.io", Version: "v1alpha1", Kind: "IngestionPolicy"}

// Get takes name of the ingestionPolicy, and returns the corresponding ingestionPolicy object, and an error if there is any.
func (c *FakeIngestionPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IngestionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ingestionpoliciesResource, c.ns, name), &v1alpha1.IngestionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngestionPolicy), err
}

// List takes label and field selectors, and returns the list of IngestionPolicies that match those selectors.
func (c *FakeIngestionPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IngestionPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ingestionpoliciesResource, ingestionpoliciesKind, c.ns, opts), &v1alpha1.IngestionPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IngestionPolicyList{ListMeta: obj.(*v1alpha1.IngestionPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.IngestionPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ingestionPolicies.
func (c *FakeIngestionPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ingestionpoliciesResource, c.ns, opts))

}

// Create takes the representation of a ingestionPolicy and creates it.  Returns the server's representation of the ingestionPolicy, and an error, if there is any.
func (c *FakeIngestionPolicies) Create(ctx context.Context, ingestionPolicy *v1alpha1.IngestionPolicy, opts v1.CreateOptions) (result *v1alpha1.IngestionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ingestionpoliciesResource, c.ns, ingestionPolicy), &v1alpha1.IngestionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngestionPolicy), err
}

// Update takes the representation of a ingestionPolicy and updates it. Returns the server's representation of the ingestionPolicy, and an error, if there is any.
func (c *FakeIngestionPolicies) Update(ctx context.Context, ingestionPolicy *v1alpha1.IngestionPolicy, opts v1.UpdateOptions) (result *v1alpha1.IngestionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ingestionpoliciesResource, c.ns, ingestionPolicy), &v1alpha1.IngestionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngestionPolicy), err
}

// Delete takes name of the ingestionPolicy and deletes it. Returns an error if one occurs.
func (c *FakeIngestionPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ingestionpoliciesResource, c.ns, name, opts), &v1alpha1.IngestionPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIngestionPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ingestionpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IngestionPolicyList{})
	return err
}

// Patch applies the patch and returns the patched ingestionPolicy.
func (c *FakeIngestionPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IngestionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ingestionpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IngestionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngestionPolicy), err
}
