// github.com/projectkeas
// Code generated by lister-gen. DO NOT EDIT.

package internalversion

// IngestionPolicyListerExpansion allows custom methods to be added to
// IngestionPolicyLister.
type IngestionPolicyListerExpansion interface{}

// IngestionPolicyNamespaceListerExpansion allows custom methods to be added to
// IngestionPolicyNamespaceLister.
type IngestionPolicyNamespaceListerExpansion interface{}
