// github.com/projectkeas
// Code generated by informer-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	time "time"

	v1alpha1 "github.com/projectkeas/crds/pkg/apis/keas.io/v1alpha1"
	internalinterfaces "github.com/projectkeas/crds/pkg/client/informers/internalversion/internalinterfaces"
	internalversion "github.com/projectkeas/crds/pkg/client/listers/v1alpha1/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	internalclientset "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset"
)

// IngestionPolicyInformer provides access to a shared informer and lister for
// IngestionPolicies.
type IngestionPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.IngestionPolicyLister
}

type ingestionPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIngestionPolicyInformer constructs a new informer for IngestionPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIngestionPolicyInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIngestionPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIngestionPolicyInformer constructs a new informer for IngestionPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIngestionPolicyInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Keas().IngestionPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Keas().IngestionPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&v1alpha1.IngestionPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *ingestionPolicyInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIngestionPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ingestionPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&v1alpha1.IngestionPolicy{}, f.defaultInformer)
}

func (f *ingestionPolicyInformer) Lister() internalversion.IngestionPolicyLister {
	return internalversion.NewIngestionPolicyLister(f.Informer().GetIndexer())
}
